[package]
name = "quick-text-panel"
version = "0.1.0"
description = "Lightweight clipboard scratchpad for Windows"
authors = ["czm"]
edition = "2021"
license = "MIT"

[package.metadata]
product-name = "Anywhere"

[lib]
name = "quick_text_panel_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-clipboard-manager = "2"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-global-shortcut = "2"
